# Generated by Django 3.1.5 on 2021-01-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='branch_id',
            new_name='bank_id',
        ),
    ]
